function result = main(varargin)
% Test case 3: Multiple intersecting fractures (thesis section 5.5.4.3).
if nargin == 1 && isstruct(varargin{1}) && isfield(varargin{1}, 'SuiteRoot')
    result = runExperiment(varargin{1});
    return
end
suiteRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(suiteRoot, 'Utils'));
result = thesisRun(suiteRoot, 'Cases', "IntersectingFractures", varargin{:});
end

function result = runExperiment(options)
% Migrated from Chapter_05/EFEM_crossinFracs/crossingFracs.m.
result = struct();

% Extract the directory containing the script

fname = 'Input/crossingFracs.xml';

params = readInput(fname);

simparams = SimulationParameters(params.SimulationParameters);

% b = BlockStructuredMesh([0.0, 1.0;0.0 1.0; 0.0 1.0],[1,1,1],1);
% mesh = b.processGeometry();
N = 80;
if options.Smoke
    N = 16;
end
L = 8;
grid = structuredMesh(N, N, 1, [0.0, L], [0.0 L], [0.0 0.1]);

if mod(N, 2) ~= 0
    error('N must be even');
end

bc = Boundaries(grid);

tol = 1e-4;

yN = abs(grid.coordinates(:, 2) - L / 2) < tol & ...
    (grid.coordinates(:, 1) < tol | abs(grid.coordinates(:, 1) - L) < tol);

xN = abs(grid.coordinates(:, 1) - L / 2) < tol & ...
    (grid.coordinates(:, 2) < tol | abs(grid.coordinates(:, 2) - L) < tol);

bc.addBC('name', "yDisp", ...
        'type', "dirichlet", ...
        'field', "node", ...
        'entityListType', "bcList", ...
        'entityList', find(yN), ...
        'variable', "displacements", ...
        'components', 2);

bc.addBC('name', "xDisp", ...
        'type', "dirichlet", ...
        'field', "node", ...
        'entityListType', "bcList", ...
        'entityList', find(xN), ...
        'variable', "displacements", ...
        'components', 1);

bc.addBC('name', "zDisp", ...
        'type', "dirichlet", ...
        'field', "surface", ...
        'entityListType', "tags", ...
        'entityList', [1, 2], ...
        'variable', "displacements", ...
        'components', 3);

bc.addBC('name', "topLoad", ...
        'type', "neumann", ...
        'field', "surface", ...
        'entityListType', "tags", ...
        'entityList', 4, ...
        'variable', "displacements", ...
        'components', 2);

bc.addBC('name', "botLoad", ...
        'type', "neumann", ...
        'field', "surface", ...
        'entityListType', "tags", ...
        'entityList', 3, ...
        'variable', "displacements", ...
        'components', 2);

bc.addBCEvent("yDisp", 'time', 0.0, 'value', 0.0);
bc.addBCEvent("xDisp", 'time', 0.0, 'value', 0.0);
bc.addBCEvent("zDisp", 'time', 0.0, 'value', 0.0);
bc.addBCEvent("topLoad", 'time', 0.0, 'value', -0.01);
bc.addBCEvent("botLoad", 'time', 0.0, 'value', 0.01);

mat = Materials(params.Materials);

printUtils = OutState('outputFile', "Output/crossFrac", "printTimes", 1, 'vtkFormat', "ascii");

% Create object handling construction of Jacobian and rhs of the model
domain = Discretizer('Boundaries', bc, ...
                     'Materials', mat, ...
                     'Grid', grid);

domain.addPhysicsSolvers(params.Solver);

solver = NonLinearImplicit('simulationparameters', simparams, ...
                           'domains', domain, ...
                           'output', printUtils);
solver.simulationLoop();
result.fractureJump = domain.getState("fractureJump");
assert(all(isfinite(result.fractureJump)));

%

end
