function mesh = structuredMesh(nx,ny,nz,Lx,Ly,Lz)
% Vectorized structured hexahedral grid

%% -------------------------------------------------
% Nodes
%% -------------------------------------------------

if nargin == 6
x = linspace(Lx(1),Lx(2),nx+1);
y = linspace(Ly(1),Ly(2),ny+1);
z = linspace(Lz(1),Lz(2),nz+1);
elseif nargin == 3
  x = nx; 
  y = ny;
  z = nz;
end

[X,Y,Z] = ndgrid(x,y,z);
coord = [X(:), Y(:), Z(:)];

% linear node numbering
nid = reshape(1:(nx+1)*(ny+1)*(nz+1), nx+1, ny+1, nz+1);

% Hexahedra
%% -------------------------------------------------
% hex = [
%     (nid(1:nx  ,1:ny  ,1:nz  ))(:), ...
%     (nid(2:nx+1,1:ny  ,1:nz  ))(:), ...
%     (nid(2:nx+1,2:ny+1,1:nz  ))(:), ...
%     (nid(1:nx  ,2:ny+1,1:nz  ))(:), ...
%     (nid(1:nx  ,1:ny  ,2:nz+1))(:), ...
%     (nid(2:nx+1,1:ny  ,2:nz+1))(:), ...
%     (nid(2:nx+1,2:ny+1,2:nz+1))(:), ...
%     (nid(1:nx  ,2:ny+1,2:nz+1))(:)
% ];
topol = [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx+2:end-nx*ny)',...
         nid(nx*ny+1:end-nx-1)',...
         nid(nx*ny+2:end-nx)',...
         nid(nx*ny+nx+1:end-1)',...
         nid(nx*ny+nx+2:end)'];

% External faces
n = nid(:,:,1);
f1 =    [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx*ny+nx+2:end)'];

n = nid(:,:,1);
f1 =    [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx*ny+nx+2:end)'];

n = nid(:,:,1);
f1 =    [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx*ny+nx+2:end)'];

n = nid(:,:,1);
f1 =    [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx*ny+nx+2:end)'];

n = nid(:,:,1);
f1 =    [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx*ny+nx+2:end)'];

n = nid(:,:,1);
f1 =    [nid(1:end-nx*ny-nx-1)',...
         nid(2:end-nx*ny-nx)',...
         nid(nx+1:end-nx*ny-1)',...
         nid(nx*ny+nx+2:end)'];



surf = [fb; ft; fs; fe; fn; fw];

surfTag = [
    ones(size(fb,1),1) * 1
    ones(size(ft,1),1) * 2
    ones(size(fs,1),1) * 3
    ones(size(fe,1),1) * 4
    ones(size(fn,1),1) * 5
    ones(size(fw,1),1) * 6
];

mesh = Mesh();
mesh.coordinates = coord;
mesh.cells = topol;
mesh.nCells = size(topol,1);
mesh.surfaces = surf;
mesh.surfaceTag = surfTag;
mesh.cellTag = ones(mesh.nCells,1);
mesh.cellNumVerts = 8*ones(mesh.nCells,1);
mesh.surfaceNumVerts = 4*ones(mesh.nCells,1);
end

