function result = thesisCompareEFEM(options)
% Migrated from Chapter_05/StickSlipThesis/EFEM_clean/EFEM/runComparison.m.
result = struct();

gresLog().setVerbosity(1);

%% EFEM stick-slip-open comparison
% The script creates two comparisons for both loading directions:
%
%   1. Fixed-c comparison of:
%        penalty
%        smooth
%        smooth regularized
%        semi-smooth
%
%   2. Augmentation sweep comparing:
%        smooth regularized
%        semi-smooth
%
% Before-bounce and after-bounce results are shown in separate panels.
%
% EFEM formulation mapping:
%
%   penalty            -> EmbeddedFractureMechanics
%   smooth             -> EFEM_PenaltyFree
%   smooth regularized -> EFEMaugmented
%   semi-smooth        -> EFEMsemismooth

%% User settings

config.fixedAugmentation = 1e0;

config.augmentationSweep = [ ...
                            1e-2, ...
                            1e-1, ...
                            1e0, ...
                            1e1, ...
                            1e2];

config.directions = ["vertical", "horizontal"];

config.scenarios = [ ...
                    "pre_bounce", ...
                    "post_bounce"];

config.scenarioLabels = [ ...
                         "before bounce", ...
                         "after bounce"];

config.endTimes = [11, 16];

%% EFEM formulations

config.methods = struct( ...
                        'id', { ...
         "smoothregularized", ...
         "semismooth"}, ...
                        'solverName', { ...
                 "EFEMaugmented", ...
                 "EFEMsemismooth"}, ...
                        'label', { ...
            "smooth regularized", ...
            "semi-smooth"}, ...
                        'color', { ...
            [0.929, 0.694, 0.125], ...
            [0.494, 0.184, 0.556]});

% Only these two formulations participate in the augmentation sweep.
config.sweepMethodIds = [ ...
                         "smoothregularized", ...
                         "semismooth"];

%% Input and output locations

config.inputFile = fullfile( ...
                            "Input", ...
                            "StickSlipOpenEFEM.xml");

config.outputDir = ".";

config.historyDir = fullfile( ...
                             config.outputDir, ...
                             "Histories");

config.figureDir = fullfile( ...
                            config.outputDir, ...
                            "Figures");

% Use a new cache file because the old script used the ID "smooth" for
% EFEMaugmented. Reusing the old cache could therefore associate results
% with the wrong formulation.
config.resultsFile = fullfile( ...
                              config.outputDir, ...
                              "efem_four_formulation_results.mat");

%% Move to the script directory

ensureDirectory(config.outputDir);
ensureDirectory(config.historyDir);
ensureDirectory(config.figureDir);

%% Load cached results

records = initializeRecords();

if isfile(config.resultsFile)
    saved = load(config.resultsFile, 'records');

    if isfield(saved, 'records')
        records = saved.records;
    end
end

%% Fixed-c formulation comparison
% Run all four formulations.

for iDirection = 1:numel(config.directions)

    direction = config.directions(iDirection);

    for iScenario = 1:numel(config.scenarios)

        scenario = config.scenarios(iScenario);
        endTime = config.endTimes(iScenario);

        for iMethod = 1:numel(config.methods)

            method = config.methods(iMethod);

            [records, wasRun] = runAndRecord( ...
                                             records, ...
                                             config, ...
                                             direction, ...
                                             scenario, ...
                                             endTime, ...
                                             method, ...
                                             config.fixedAugmentation);

            if wasRun
                save( ...
                     config.resultsFile, ...
                     'records', ...
                     'config', ...
                     '-v7.3');
            end
        end
    end
end

%% Smooth-regularized and semi-smooth augmentation sweep

methodIds = string({config.methods.id});

sweepMethods = config.methods( ...
                              ismember(methodIds, config.sweepMethodIds));

for iDirection = 1:numel(config.directions)

    direction = config.directions(iDirection);

    for iScenario = 1:numel(config.scenarios)

        scenario = config.scenarios(iScenario);
        endTime = config.endTimes(iScenario);

        for iMethod = 1:numel(sweepMethods)

            method = sweepMethods(iMethod);

            for augmentation = config.augmentationSweep

                [records, wasRun] = runAndRecord( ...
                                                 records, ...
                                                 config, ...
                                                 direction, ...
                                                 scenario, ...
                                                 endTime, ...
                                                 method, ...
                                                 augmentation);

                if wasRun
                    save( ...
                         config.resultsFile, ...
                         'records', ...
                         'config', ...
                         '-v7.3');
                end
            end
        end
    end
end

%% Figures

for direction = config.directions

    plotFixedComparison( ...
                        records, ...
                        config, ...
                        direction);

    plotAugmentationSweep( ...
                          records, ...
                          config, ...
                          direction, ...
                          sweepMethods);
end

fprintf('\nEFEM comparison complete.\n');
fprintf('Results: %s\n', config.resultsFile);
fprintf('Figures: %s\n', config.figureDir);

%% Local functions

result.records = records;
result.failedConfigurations = sum(~[records.success]);
end

function records = initializeRecords()

records = struct( ...
                 'direction', {}, ...
                 'scenario', {}, ...
                 'method', {}, ...
                 'solverName', {}, ...
                 'augmentation', {}, ...
                 'iterations', {}, ...
                                      'success', {}, ...
                 'message', {}, ...
                 'historyFile', {});

end

function [records, wasRun] = runAndRecord( ...
                                          records, config, direction, scenario, endTime, method, augmentation)

idx = findRecord( ...
                 records, ...
                 direction, ...
                 scenario, ...
                 method.id, ...
                 augmentation);

wasRun = true;

fprintf( ...
        '\n%s | %s | %s | c = %.4e\n', ...
        upper(direction), ...
        scenario, ...
        method.label, ...
        augmentation);

tag = sprintf( ...
              '%s_%s_%s_c_%s', ...
              direction, ...
              scenario, ...
              method.id, ...
              scientificTag(augmentation));

historyBase = fullfile( ...
                       config.historyDir, ...
                       "EFEM_" + tag);

entry.direction = direction;
entry.scenario = scenario;
entry.method = method.id;
entry.solverName = method.solverName;
entry.augmentation = augmentation;
entry.iterations = NaN;
entry.success = false;
entry.message = "";
entry.historyFile = historyBase + ".mat";

try

    [solver, centers] = runCase( ...
                                config, ...
                                direction, ...
                                endTime, ...
                                method.solverName, ...
                                augmentation, ...
                                historyBase);

    entry.iterations = solver.totIter;
    entry.success = true;

    appendPlotStepMetadata( ...
                           entry.historyFile, ...
                           centers, ...
                           direction, ...
                           scenario, ...
                           method.label, ...
                           augmentation, ...
                           "EFEM");

    fprintf('iterations = %g\n', entry.iterations);

catch ME
    entry.success = false;

    entry.message = string( ...
                           ME.getReport( ...
                   'extended', ...
                   'hyperlinks', ...
                   'off'));

    fprintf(2, 'FAILED: %s\n', ME.message);
end

if isempty(idx)
    records(end + 1) = entry; %#ok<AGROW>
else
    records(idx) = entry;
end

wasRun = true;

end

function idx = findRecord( ...
                          records, direction, scenario, method, augmentation)

idx = [];

if isempty(records)
    return
end

same = [records.direction] == direction & ...
  [records.scenario] == scenario & ...
  [records.method] == method & ...
  abs([records.augmentation] - augmentation) <= ...
  10 * eps(max(1, abs(augmentation)));

idx = find(same, 1, 'last');

end

function [solver, centers] = runCase( ...
                                     config, direction, endTime, formulation, augmentation, historyBase)

if exist(formulation, 'class') ~= 8

    error( ...
          'EFEM:MissingFormulation', ...
          ['The GReS formulation class "%s" is not on the MATLAB path. ', ...
                 'Update config.methods.solverName if your fork uses another name.'], ...
          formulation);
end

%% Read EFEM input

params = readInput(config.inputFile);

%% Original EFEM geometry and mesh

X = 5;
Y = 10;
Z = 15;

ny = 10;
nz = 12;

grid = structuredMesh( ...
                      [3, 3, 3], ...
                      ny, ...
                      nz, ...
                      [0, 0.45 * X, 0.55 * X, X], ...
                      [0, Y], ...
                      [0, Z]);

assert( ...
       mod(ny, 2) == 0, ...
       'The number of elements along the y axis must be even.');

%% Simulation parameters and materials

params.SimulationParameters.End = endTime;

simParam = SimulationParameters( ...
                                params.SimulationParameters);

materials = Materials(params.Materials);

%% Boundary conditions

switch direction

    case "vertical"

        boundaries = setVerticalBC( ...
                                   Y, ...
                                   grid);

    case "horizontal"

        boundaries = setHorizontalBC( ...
                                     Y, ...
                                     grid);

    otherwise

        error( ...
              'EFEM:LoadingDirection', ...
              'Unknown loading direction: %s', ...
              direction);
end

%% Original single EFEM domain

domain = Discretizer( ...
                     'boundaries', boundaries, ...
                     'materials', materials, ...
                     'grid', grid);

%% Add selected EFEM physics solver
% Keep the EFEM input structure from StickSlipOpenEFEM.xml.

E = materials.getConstitutiveLaw(1).E;
augmentation = augmentation * E;

efemInput = params.EFEM;

efemInput.augmentation = augmentation;
efemInput.augmentationNormal = augmentation;
efemInput.augmentationTangential = augmentation;

domain.addPhysicsSolver( ...
                        formulation, ...
                        efemInput);

%% Initial stress

stress = domain.getState("stress");
stress(:, 1) = -1.0;
domain.setState(stress, "stress");

%% Output history

printTimes = 0:endTime;

output = OutState( ...
                  'outputFile', historyBase, ...
                  'printTimes', printTimes, ...
                  'matFileName', historyBase, ...
                  'saveHistory', 1, ...
                  'solvePrintTimes', 1);

%% Nonlinear solution

solver = NonLinearImplicit( ...
                           'simulationparameters', simParam, ...
                           'domains', domain, ...
                           'output', output);

solver.simulationLoop();

%% EFEM fracture-cell centers

centers = [];

efemSolver = getPhysicsSolver( ...
                              domain, ...
                              formulation);

if isprop(efemSolver, 'fractureMesh')
    centers = efemSolver.fractureMesh.surfaces.center;
end

end

function appendPlotStepMetadata( ...
                                matFile, centers, direction, scenario, method, augmentation, model)

if ~isfile(matFile)

    warning( ...
            'EFEM:MissingHistory', ...
            'History MAT file was not found: %s', ...
            matFile);

    return
end

plotStepMeta = struct( ...
                      'model', model, ...
                      'centers', centers, ...
                      'verticalCoordinate', 3, ...
                      'transverseCoordinate', 2, ...
                      'direction', direction, ...
                      'scenario', scenario, ...
                      'method', method, ...
                      'augmentation', augmentation);

save( ...
     matFile, ...
     'plotStepMeta', ...
     '-append');

end

function plotFixedComparison(records, config, direction)

fig = comparisonFigure( ...
                       direction + " loading - fixed augmentation");

layout = tiledlayout( ...
                     fig, ...
                     1, ...
                     2, ...
                     'TileSpacing', 'compact', ...
                     'Padding', 'compact');

title( ...
      layout, ...
      sprintf( ...
          '%s loading, $c = 10^{%d}$', ...
          direction, ...
          round(log10(config.fixedAugmentation))), ...
      'Interpreter', 'latex', ...
      'FontSize', 18);

for iScenario = 1:numel(config.scenarios)

    ax = nexttile(layout, iScenario);

    values = nan(1, numel(config.methods));

    for iMethod = 1:numel(config.methods)

        rec = getRecord( ...
                        records, ...
                        direction, ...
                        config.scenarios(iScenario), ...
                        config.methods(iMethod).id, ...
                        config.fixedAugmentation);

        if ~isempty(rec) && rec.success
            values(iMethod) = rec.iterations;
        end
    end

    labels = string({config.methods.label});
    colors = vertcat(config.methods.color);

    drawBars( ...
             ax, ...
             values, ...
             labels, ...
             colors);

    title( ...
          ax, ...
          config.scenarioLabels(iScenario), ...
          'Interpreter', 'latex', ...
          'FontSize', 15);

    xlabel( ...
           ax, ...
           'EFEM formulation', ...
           'Interpreter', 'latex', ...
           'FontSize', 14);
end

name = sprintf( ...
               'efem_%s_formulations_fixed_c.pdf', ...
               direction);

exportgraphics( ...
               fig, ...
               fullfile(config.figureDir, name), ...
               'ContentType', 'vector');

end

function plotAugmentationSweep(records, config, direction, methods)

fig = comparisonFigure( ...
                       direction + " loading - augmentation sweep");

layout = tiledlayout( ...
                     fig, ...
                     1, ...
                     2, ...
                     'TileSpacing', 'compact', ...
                     'Padding', 'compact');

title( ...
      layout, ...
      direction + ...
      " loading - smooth-regularized and semi-smooth sweep", ...
      'Interpreter', 'latex', ...
      'FontSize', 18);

for iScenario = 1:numel(config.scenarios)

    ax = nexttile(layout, iScenario);

    % Rows correspond to augmentation values.
    % Columns correspond to the two formulations.
    values = nan( ...
                 numel(config.augmentationSweep), ...
                 numel(methods));

    for iMethod = 1:numel(methods)

        for iAugmentation = 1:numel(config.augmentationSweep)

            rec = getRecord( ...
                            records, ...
                            direction, ...
                            config.scenarios(iScenario), ...
                            methods(iMethod).id, ...
                            config.augmentationSweep(iAugmentation));

            if ~isempty(rec) && rec.success
                values(iAugmentation, iMethod) = rec.iterations;
            end
        end
    end

    labels = compose( ...
                     '$10^{%d}$', ...
                     round(log10(config.augmentationSweep)));

    colors = vertcat(methods.color);
    methodLabels = string({methods.label});

    drawGroupedSweepBars( ...
                         ax, ...
                         values, ...
                         labels, ...
                         colors, ...
                         methodLabels);

    title( ...
          ax, ...
          config.scenarioLabels(iScenario), ...
          'Interpreter', 'latex', ...
          'FontSize', 15);

    xlabel( ...
           ax, ...
           'augmentation parameter $c$', ...
           'Interpreter', 'latex', ...
           'FontSize', 14);
end

name = sprintf( ...
               'efem_%s_augmentation_sweep.pdf', ...
               direction);

exportgraphics( ...
               fig, ...
               fullfile(config.figureDir, name), ...
               'ContentType', 'vector');

end

function fig = comparisonFigure(figureName)

fig = figure( ...
             'Name', char(figureName), ...
             'Color', 'w', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.15, 0.90, 0.65]);

end

function drawBars( ...
                  ax, values, labels, colors)

hold(ax, 'on');
box(ax, 'on');
grid(ax, 'on');

finiteValues = values(isfinite(values));

if isempty(finiteValues)
    yMax = 1;
else
    yMax = max(finiteValues);
end

dummyHeight = max(0.025 * yMax, 0.5);

% Spread the four fixed-c bars so that the formulation labels do not
% overlap. All markers and annotations use the same x coordinates.
barSpacing = 1.75;
xPositions = (1:numel(values)) * barSpacing;
barWidth = 0.55;

for i = 1:numel(values)

    failed = ~isfinite(values(i));

    if failed
        height = dummyHeight;
    else
        height = values(i);
    end

    bar( ...
        ax, ...
        xPositions(i), ...
        height, ...
        barWidth, ...
        'FaceColor', colors(i, :), ...
        'EdgeColor', [0.15, 0.15, 0.15], ...
        'LineWidth', 0.8);

    if failed

        plot( ...
             ax, ...
             xPositions(i), ...
             height + 0.02 * yMax, ...
             'rx', ...
             'MarkerSize', 9, ...
             'LineWidth', 1.8, ...
             'HandleVisibility', 'off');

        text( ...
             ax, ...
             xPositions(i), ...
             height + 0.055 * yMax, ...
             'fail', ...
             'Interpreter', 'latex', ...
             'HorizontalAlignment', 'center', ...
             'VerticalAlignment', 'bottom', ...
             'FontSize', 11);

    end
end

ax.XTick = xPositions;
ax.XTickLabel = labels;
ax.XTickLabelRotation = 15;
ax.TickLabelInterpreter = 'latex';
ax.FontSize = 11;

xlim( ...
     ax, ...
     [xPositions(1) - 0.7 * barSpacing, ...
          xPositions(end) + 0.7 * barSpacing]);

ylim( ...
     ax, ...
     [0, max(1, 1.22 * yMax)]);

ylabel( ...
       ax, ...
       'total nonlinear iterations', ...
       'Interpreter', 'latex', ...
       'FontSize', 14);

end

function drawGroupedSweepBars( ...
                              ax, values, labels, colors, methodLabels)

hold(ax, 'on');
box(ax, 'on');
grid(ax, 'on');

finiteValues = values(isfinite(values));

if isempty(finiteValues)
    yMax = 1;
else
    yMax = max(finiteValues);
end

dummyHeight = max(0.025 * yMax, 0.5);

nGroups = size(values, 1);
nMethods = size(values, 2);

% Narrow paired bars with a visible space between the formulations.
barWidth = min( ...
               0.28, ...
               0.64 / max(1, nMethods));

if nMethods == 1

    offsets = 0;

else

    offsets = ((1:nMethods) - (nMethods + 1) / 2) ...
      * (barWidth + 0.06);
end

barHandles = gobjects(1, nMethods);

for iMethod = 1:nMethods

    x = (1:nGroups) + offsets(iMethod);

    heights = values(:, iMethod).';
    failed = ~isfinite(heights);

    heights(failed) = dummyHeight;

    barHandles(iMethod) = bar( ...
                              ax, ...
                              x, ...
                              heights, ...
                              barWidth, ...
                              'FaceColor', colors(iMethod, :), ...
                              'EdgeColor', [0.15, 0.15, 0.15], ...
                              'LineWidth', 0.8);

    for iGroup = 1:nGroups

        if failed(iGroup)

            plot( ...
                 ax, ...
                 x(iGroup), ...
                 heights(iGroup) + 0.02 * yMax, ...
                 'rx', ...
                 'MarkerSize', 9, ...
                 'LineWidth', 1.8, ...
                 'HandleVisibility', 'off');

            text( ...
                 ax, ...
                 x(iGroup), ...
                 heights(iGroup) + 0.055 * yMax, ...
                 'fail', ...
                 'Interpreter', 'latex', ...
                 'HorizontalAlignment', 'center', ...
                 'VerticalAlignment', 'bottom', ...
                 'FontSize', 10);

        end
    end
end

ax.XTick = 1:nGroups;
ax.XTickLabel = labels;
ax.TickLabelInterpreter = 'latex';
ax.FontSize = 11;

xlim( ...
     ax, ...
     [0.5, nGroups + 0.5]);

ylim( ...
     ax, ...
     [0, max(1, 1.22 * yMax)]);

ylabel( ...
       ax, ...
       'total nonlinear iterations', ...
       'Interpreter', 'latex', ...
       'FontSize', 14);

legend( ...
       ax, ...
       barHandles, ...
       methodLabels, ...
       'Interpreter', 'latex', ...
       'Location', 'best', ...
       'FontSize', 11);

end

function rec = getRecord( ...
                         records, direction, scenario, method, augmentation)

idx = findRecord( ...
                 records, ...
                 direction, ...
                 scenario, ...
                 method, ...
                 augmentation);

if isempty(idx)
    rec = [];
else
    rec = records(idx);
end

end

function tag = scientificTag(value)

tag = replace( ...
              string(sprintf('%.0e', value)), ...
              ["+", "-"], ...
              ["p", "m"]);

end

function ensureDirectory(pathName)

if ~isfolder(pathName)
    mkdir(pathName);
end

end

function bc = setVerticalBC(Y, grid)

targetCoord = 0.5 * Y;

n = abs(grid.coordinates(:, 2) - targetCoord) < 1e-4 & ...
  abs(grid.coordinates(:, 3)) < 1e-4;

nList = find(n);

bc = Boundaries(grid);

bc.addBC( ...
         'name', "fixBack", ...
         'type', "dirichlet", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "tag", ...
         'entityList', 5, ...
         'components', "x");

bc.addBCEvent( ...
              "fixBack", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBC( ...
         'name', "y_bottom", ...
         'type', "dirichlet", ...
         'field', "node", ...
         'variable', "displacements", ...
         'entityListType', "bcList", ...
         'entityList', nList, ...
         'components', "y");

bc.addBCEvent( ...
              "y_bottom", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBC( ...
         'name', "z_bottom", ...
         'type', "dirichlet", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "tag", ...
         'entityList', 1, ...
         'components', "z");

bc.addBCEvent( ...
              "z_bottom", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBC( ...
         'name', "x_load", ...
         'type', "neumann", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "tag", ...
         'entityList', 6, ...
         'components', "x");

addNormalLoadEvents(bc);

centers = grid.surfaces.center;

sList = find( ...
             centers(:, 1) > 2.5 & ...
             centers(:, 3) > 14.99);

bc.addBC( ...
         'name', "z_load", ...
         'type', "neumann", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "bcList", ...
         'entityList', sList, ...
         'components', "z");

bc.addBCEvent( ...
              "z_load", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "z_load", ...
              'time', 1.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "z_load", ...
              'time', 6.0, ...
              'value', -18.0);

bc.addBCEvent( ...
              "z_load", ...
              'time', 11.0, ...
              'value', -18.0);

bc.addBCEvent( ...
              "z_load", ...
              'time', 16.0, ...
              'value', 0.0);

end

function bc = setHorizontalBC(Y, grid)

targetCoord = 0.5 * Y;

n = abs(grid.coordinates(:, 2) - targetCoord) < 1e-4 & ...
  abs(grid.coordinates(:, 3)) < 1e-4;

nList = find(n);

bc = Boundaries(grid);

bc.addBC( ...
         'name', "fixBack", ...
         'type', "dirichlet", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "tag", ...
         'entityList', 5, ...
         'components', "x");

bc.addBCEvent( ...
              "fixBack", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBC( ...
         'name', "y_bottom", ...
         'type', "dirichlet", ...
         'field', "node", ...
         'variable', "displacements", ...
         'entityListType', "bcList", ...
         'entityList', nList, ...
         'components', "y");

bc.addBCEvent( ...
              "y_bottom", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBC( ...
         'name', "z_bottom", ...
         'type', "dirichlet", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "tag", ...
         'entityList', 1, ...
         'components', "z");

bc.addBCEvent( ...
              "z_bottom", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBC( ...
         'name', "x_load", ...
         'type', "neumann", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "tag", ...
         'entityList', 6, ...
         'components', "x");

addNormalLoadEvents(bc);

centers = grid.surfaces.center;

sList = find( ...
             centers(:, 1) > 2.5 & ...
             centers(:, 3) > 14.99);

bc.addBC( ...
         'name', "y_load", ...
         'type', "neumann", ...
         'field', "surface", ...
         'variable', "displacements", ...
         'entityListType', "bcList", ...
         'entityList', sList, ...
         'components', "y");

bc.addBCEvent( ...
              "y_load", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "y_load", ...
              'time', 1.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "y_load", ...
              'time', 6.0, ...
              'value', 5.0);

bc.addBCEvent( ...
              "y_load", ...
              'time', 11.0, ...
              'value', 5.0);

bc.addBCEvent( ...
              "y_load", ...
              'time', 16.0, ...
              'value', 0.0);

end

function addNormalLoadEvents(bc)

bc.addBCEvent( ...
              "x_load", ...
              'time', 0.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "x_load", ...
              'time', 1.0, ...
              'value', -5.0);

bc.addBCEvent( ...
              "x_load", ...
              'time', 6.0, ...
              'value', -5.0);

bc.addBCEvent( ...
              "x_load", ...
              'time', 11.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "x_load", ...
              'time', 16.0, ...
              'value', 0.0);

bc.addBCEvent( ...
              "x_load", ...
              'time', 20.0, ...
              'value', 1.0);

end
