%% STEP 1) SINGLE PHYSICS - SINGLE PHASE FLOW




%% STEP 2) COUPLING WITH MECHANICS

%% STEP 3) USING SUBDOMAINS

%% STEP 4) ADDING A NON-CONFORMING INTERFACE

%% STEP 5) CONTACT MECHANICS AND EMBEDDED FRACTURES