name: MATLAB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matlab-tests:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup MATLAB (handles licensing automatically)
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      # 3. Run setup scripts and main test script
      - name: Initialize, compile, and run tests
        uses: matlab-actions/run-command@v2
        with:
          command: |
            try
                initGReS;

                compileAll;

                runIntegratedTest;
            catch ME
                disp(getReport(ME));
                exit(1); % fail CI
            end
