name: Management MATLAB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gres_tests:
    name: ${{ matrix.display_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            display_name: Linux (Ubuntu Latest, GCC 11)
          - os: windows-latest
            display_name: Windows (Windows 2022, MSVC 2022)

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Ensure GCC 11 is active on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
          gcc --version
          g++ --version

      - name: Initialize GReS, compile MEX, and run tests
        uses: matlab-actions/run-command@v2
        with:
          command: |
            try
                initGReS;
                compileAll;
                run("Code/unittest/runUnitTests.m");
                run("Code/integratedTest/runIntegratedTests.m");
            catch ME
                disp(getReport(ME));
                exit(1); % Mark job as failed
            end

  aggregate:
    name: check_all_tests_passed
    runs-on: ubuntu-latest
    needs: [gres_tests]
    steps:
      - name: All platform tests passed
        run: echo "All tests succeeded on all platforms"
