name: MATLAB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matlab-tests:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup MATLAB
      #    (This uses the official MathWorks action to set up MATLAB)
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      # 3. Run your main test script
      - name: Run MATLAB test script
        run: |
          matlab -batch "try, run('Tests/folder_names/Main.m'); catch ME, disp(getReport(ME)); exit(1); end"

      # 4. (Optional) If you have multiple folders of tests, loop through them
      #    Example of running all Main.m files under Tests/**/
      # - name: Run all test scripts in subfolders
      #   run: |
      #     find Tests -type f -name "Main.m" | while read testfile; do
      #       echo "Running $testfile"
      #       matlab -batch "try, run('$testfile'); catch ME, disp(getReport(ME)); exit(1); end"
      #     done
